// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadL2radar returns the embedded CollectionSpec for l2radar.
func loadL2radar() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_L2radarBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load l2radar: %w", err)
	}

	return spec, err
}

// loadL2radarObjects loads l2radar and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*l2radarObjects
//	*l2radarPrograms
//	*l2radarMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadL2radarObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadL2radar()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// l2radarSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type l2radarSpecs struct {
	l2radarProgramSpecs
	l2radarMapSpecs
	l2radarVariableSpecs
}

// l2radarProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type l2radarProgramSpecs struct {
	L2radar *ebpf.ProgramSpec `ebpf:"l2radar"`
}

// l2radarMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type l2radarMapSpecs struct {
}

// l2radarVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type l2radarVariableSpecs struct {
}

// l2radarObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadL2radarObjects or ebpf.CollectionSpec.LoadAndAssign.
type l2radarObjects struct {
	l2radarPrograms
	l2radarMaps
	l2radarVariables
}

func (o *l2radarObjects) Close() error {
	return _L2radarClose(
		&o.l2radarPrograms,
		&o.l2radarMaps,
	)
}

// l2radarMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadL2radarObjects or ebpf.CollectionSpec.LoadAndAssign.
type l2radarMaps struct {
}

func (m *l2radarMaps) Close() error {
	return _L2radarClose()
}

// l2radarVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadL2radarObjects or ebpf.CollectionSpec.LoadAndAssign.
type l2radarVariables struct {
}

// l2radarPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadL2radarObjects or ebpf.CollectionSpec.LoadAndAssign.
type l2radarPrograms struct {
	L2radar *ebpf.Program `ebpf:"l2radar"`
}

func (p *l2radarPrograms) Close() error {
	return _L2radarClose(
		p.L2radar,
	)
}

func _L2radarClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed l2radar_bpfeb.o
var _L2radarBytes []byte
